### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by AbhishekBishoyi** [lucywang720/model-surgery#1]
Hi,

Thank you for the great work.

However, Perspective API key is committed: https://github.com/lucywang720/model-surgery/blob/7a5bf76218aa9f4c5ecb76383bc4638ebebad8b7/main/eval/eval/api_key#L1

The key may have been compromised.

**Comment by lucywang720** [comment]
Thank you very much for your kind reminder. We have removed the content from the API key file and deactivated this API key. And we would like to express our gratitude once again!

**Comment by AbhishekBishoyi** [comment]
I am closing this issue.
